import { Problem } from '../core/types';

export const PROBLEMS: Problem[] = [
  // ================= VARIABLES & TYPES =================
  {
    id: 'js-vars-01',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'variables_types',
    secondaryConcepts: [],
    title: 'Calculate Total Cost',
    statement: 'Write a function `totalCost(price, quantity)` that calculates and returns the total cost by multiplying the price by the quantity.',
    example: 'totalCost(10, 3) returns 30.',
    starterCode: 'function totalCost(price, quantity) {\n  // your code here\n}\n',
    functionName: 'totalCost',
    visibleTests: [
      { id: 't1', args: [10, 3], expected: 30 },
      { id: 't2', args: [5, 0], expected: 0 },
      { id: 't3', args: [7, 4], expected: 28 },
      { id: 't4', args: [12, 1], expected: 12 },
      { id: 't5', args: [25, 4], expected: 100 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: 0, max: 100 },
        { gen: 'intInRange', min: 0, max: 100 },
      ],
      edgeCases: [[0, 0], [1, 1], [0, 50], [99, 100]],
    },
    referenceSolution: 'function totalCost(price, quantity) {\n  return price * quantity;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Think about what math operation combines price and item quantity.',
      'In JavaScript, use the asterisk symbol to multiply two numbers together.',
      'Multiply price by quantity and use the return keyword to return the result.',
    ],
    conceptNote: 'Variables store values such as numbers or text. You can perform basic arithmetic with operators like + (add), - (subtract), and * (multiply). A function must return its final answer.',
    commonMistakes: [
      {
        tag: 'wrong_operator',
        variantCode: 'function totalCost(price, quantity) {\n  return price + quantity;\n}\n',
      },
      {
        tag: 'missing_return',
        variantCode: 'function totalCost(price, quantity) {\n  const total = price * quantity;\n}\n',
      },
    ],
    difficulty: 1,
    order: 1,
  },
  {
    id: 'js-vars-02',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'variables_types',
    secondaryConcepts: [],
    title: 'Discounted Price',
    statement: 'Write a function `discountedPrice(originalPrice, discount)` that returns the price after subtracting the discount.',
    example: 'discountedPrice(100, 20) returns 80.',
    starterCode: 'function discountedPrice(originalPrice, discount) {\n  // your code here\n}\n',
    functionName: 'discountedPrice',
    visibleTests: [
      { id: 't1', args: [100, 20], expected: 80 },
      { id: 't2', args: [50, 50], expected: 0 },
      { id: 't3', args: [45, 10], expected: 35 },
      { id: 't4', args: [80, 0], expected: 80 },
      { id: 't5', args: [200, 75], expected: 125 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: 50, max: 200 },
        { gen: 'intInRange', min: 0, max: 50 },
      ],
      edgeCases: [[100, 0], [50, 50], [0, 0]],
    },
    referenceSolution: 'function discountedPrice(originalPrice, discount) {\n  return originalPrice - discount;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'A discount reduces the price. Which operator takes away one number from another?',
      'Take the discount away from the first price parameter.',
      'Return the starting price minus the discount amount.',
    ],
    conceptNote: 'Subtractive operations use the minus operator. Be sure the first value is the starting price.',
    commonMistakes: [
      {
        tag: 'wrong_operator',
        variantCode: 'function discountedPrice(originalPrice, discount) {\n  return originalPrice + discount;\n}\n',
      },
      {
        tag: 'missing_return',
        variantCode: 'function discountedPrice(originalPrice, discount) {\n  const res = originalPrice - discount;\n}\n',
      },
    ],
    difficulty: 1,
    order: 2,
    variantOf: 'js-vars-01',
  },
  {
    id: 'js-vars-03',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'variables_types',
    secondaryConcepts: [],
    title: 'Rectangle Area',
    statement: 'Write a function `rectArea(width, height)` that calculates and returns the area of a rectangle.',
    example: 'rectArea(5, 4) returns 20.',
    starterCode: 'function rectArea(width, height) {\n  // your code here\n}\n',
    functionName: 'rectArea',
    visibleTests: [
      { id: 't1', args: [5, 4], expected: 20 },
      { id: 't2', args: [10, 10], expected: 100 },
      { id: 't3', args: [3, 7], expected: 21 },
      { id: 't4', args: [0, 8], expected: 0 },
      { id: 't5', args: [12, 5], expected: 60 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: 0, max: 100 },
        { gen: 'intInRange', min: 0, max: 100 },
      ],
      edgeCases: [[0, 10], [1, 1], [50, 50]],
    },
    referenceSolution: 'function rectArea(width, height) {\n  return width * height;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'The area of a rectangle is found by multiplying its two dimensions.',
      'Multiply the width by the height.',
      'Return the calculated product from your function.',
    ],
    conceptNote: 'Multiplication uses the asterisk (*) operator.',
    commonMistakes: [
      {
        tag: 'wrong_operator',
        variantCode: 'function rectArea(width, height) {\n  return (width + height) * 2;\n}\n',
      },
      {
        tag: 'missing_return',
        variantCode: 'function rectArea(width, height) {\n  const area = width * height;\n}\n',
      },
    ],
    difficulty: 1,
    order: 3,
    variantOf: 'js-vars-01',
  },
  {
    id: 'js-vars-04',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'variables_types',
    secondaryConcepts: [],
    title: 'Change Due',
    statement: 'Write a function `changeDue(bill, paid)` that returns the amount of change to return to a customer after paying.',
    example: 'changeDue(35, 50) returns 15.',
    starterCode: 'function changeDue(bill, paid) {\n  // your code here\n}\n',
    functionName: 'changeDue',
    visibleTests: [
      { id: 't1', args: [35, 50], expected: 15 },
      { id: 't2', args: [20, 20], expected: 0 },
      { id: 't3', args: [15, 100], expected: 85 },
      { id: 't4', args: [8, 10], expected: 2 },
      { id: 't5', args: [64, 100], expected: 36 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: 1, max: 50 },
        { gen: 'intInRange', min: 50, max: 200 },
      ],
      edgeCases: [[50, 50], [1, 100]],
    },
    referenceSolution: 'function changeDue(bill, paid) {\n  return paid - bill;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Change is what remains when you subtract the bill from the money provided.',
      'Take away the bill amount from the paid amount.',
      'Return the difference after subtracting.',
    ],
    conceptNote: 'Order matters in subtraction: paid minus bill.',
    commonMistakes: [
      {
        tag: 'wrong_operator',
        variantCode: 'function changeDue(bill, paid) {\n  return bill - paid;\n}\n',
      },
      {
        tag: 'missing_return',
        variantCode: 'function changeDue(bill, paid) {\n  const diff = paid - bill;\n}\n',
      },
    ],
    difficulty: 1,
    order: 4,
    variantOf: 'js-vars-01',
  },
  {
    id: 'js-vars-05',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'variables_types',
    secondaryConcepts: [],
    title: 'Minutes to Seconds',
    statement: 'Write a function `minutesToSeconds(minutes)` that converts a count of minutes into seconds (60 seconds per minute).',
    example: 'minutesToSeconds(3) returns 180.',
    starterCode: 'function minutesToSeconds(minutes) {\n  // your code here\n}\n',
    functionName: 'minutesToSeconds',
    visibleTests: [
      { id: 't1', args: [3], expected: 180 },
      { id: 't2', args: [0], expected: 0 },
      { id: 't3', args: [1], expected: 60 },
      { id: 't4', args: [10], expected: 600 },
      { id: 't5', args: [5], expected: 300 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 0, max: 120 }],
      edgeCases: [[0], [1], [60]],
    },
    referenceSolution: 'function minutesToSeconds(minutes) {\n  return minutes * 60;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Each minute contains sixty seconds.',
      'Multiply the minutes parameter by sixty.',
      'Calculate the total seconds by multiplying.',
    ],
    conceptNote: 'Constants like 60 can be multiplied directly with input variables.',
    commonMistakes: [
      {
        tag: 'wrong_operator',
        variantCode: 'function minutesToSeconds(minutes) {\n  return minutes + 60;\n}\n',
      },
      {
        tag: 'missing_return',
        variantCode: 'function minutesToSeconds(minutes) {\n  const s = minutes * 60;\n}\n',
      },
    ],
    difficulty: 1,
    order: 5,
    variantOf: 'js-vars-01',
  },

  // ================= CONDITIONALS =================
  {
    id: 'js-cond-01',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'conditionals',
    secondaryConcepts: [],
    title: 'Movie Ticket Price',
    statement: 'Write a function `ticketPrice(age)` that returns the ticket price: age 12 or under pays 5, age 60 or over pays 6, and everyone else pays 10.',
    example: 'ticketPrice(8) returns 5; ticketPrice(65) returns 6; ticketPrice(25) returns 10.',
    starterCode: 'function ticketPrice(age) {\n  // your code here\n}\n',
    functionName: 'ticketPrice',
    visibleTests: [
      { id: 't1', args: [10], expected: 5 },
      { id: 't2', args: [12], expected: 5 },
      { id: 't3', args: [60], expected: 6 },
      { id: 't4', args: [65], expected: 6 },
      { id: 't5', args: [25], expected: 10 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 0, max: 100 }],
      edgeCases: [[0], [12], [13], [59], [60], [100]],
    },
    referenceSolution: 'function ticketPrice(age) {\n  if (age <= 12) return 5;\n  if (age >= 60) return 6;\n  return 10;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Check the different age brackets using conditional branches.',
      'Compare age to twelve for children and sixty for seniors.',
      'Output five for kids, six for seniors, or ten for adults.',
    ],
    conceptNote: 'Conditionals let code branch and choose different actions. Check boundary numbers carefully with <= or >=.',
    commonMistakes: [
      {
        tag: 'boundary_off_by_one',
        variantCode: 'function ticketPrice(age) {\n  if (age < 12) return 5;\n  if (age > 60) return 6;\n  return 10;\n}\n',
      },
      {
        tag: 'missing_return',
        variantCode: 'function ticketPrice(age) {\n  if (age <= 12) { 5; } else if (age >= 60) { 6; } else { 10; }\n}\n',
      },
    ],
    difficulty: 1,
    order: 1,
  },
  {
    id: 'js-cond-02',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'conditionals',
    secondaryConcepts: [],
    title: 'Shipping Fee',
    statement: 'Write a function `shippingFee(weight)` that calculates fee: weight up to 2 kg pays 50, weight up to 10 kg pays 100, and over 10 kg pays 200.',
    example: 'shippingFee(1) returns 50; shippingFee(5) returns 100; shippingFee(15) returns 200.',
    starterCode: 'function shippingFee(weight) {\n  // your code here\n}\n',
    functionName: 'shippingFee',
    visibleTests: [
      { id: 't1', args: [1], expected: 50 },
      { id: 't2', args: [2], expected: 50 },
      { id: 't3', args: [7], expected: 100 },
      { id: 't4', args: [10], expected: 100 },
      { id: 't5', args: [15], expected: 200 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 1, max: 30 }],
      edgeCases: [[1], [2], [3], [10], [11], [25]],
    },
    referenceSolution: 'function shippingFee(weight) {\n  if (weight <= 2) return 50;\n  if (weight <= 10) return 100;\n  return 200;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Check the package weight against each tier.',
      'Use conditional statements to test if weight is at most two or ten.',
      'Give back fifty for light parcels, one hundred for medium, or two hundred for heavy.',
    ],
    conceptNote: 'Order conditions from smallest range to largest range.',
    commonMistakes: [
      {
        tag: 'boundary_off_by_one',
        variantCode: 'function shippingFee(weight) {\n  if (weight < 2) return 50;\n  if (weight < 10) return 100;\n  return 200;\n}\n',
      },
    ],
    difficulty: 1,
    order: 2,
    variantOf: 'js-cond-01',
  },
  {
    id: 'js-cond-03',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'conditionals',
    secondaryConcepts: [],
    title: 'Pass or Fail',
    statement: 'Write a function `passOrFail(score)` that returns "pass" if score is 75 or above, and "fail" otherwise.',
    example: 'passOrFail(80) returns "pass"; passOrFail(70) returns "fail".',
    starterCode: 'function passOrFail(score) {\n  // your code here\n}\n',
    functionName: 'passOrFail',
    visibleTests: [
      { id: 't1', args: [75], expected: 'pass' },
      { id: 't2', args: [80], expected: 'pass' },
      { id: 't3', args: [74], expected: 'fail' },
      { id: 't4', args: [100], expected: 'pass' },
      { id: 't5', args: [50], expected: 'fail' },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 0, max: 100 }],
      edgeCases: [[0], [74], [75], [76], [100]],
    },
    referenceSolution: 'function passOrFail(score) {\n  if (score >= 75) return "pass";\n  return "fail";\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Compare the numerical grade with seventy-five.',
      'Use a conditional check to see if passing threshold is met.',
      'Output the passing or failing string accordingly.',
    ],
    conceptNote: 'Strings must be enclosed in quotes.',
    commonMistakes: [
      {
        tag: 'boundary_off_by_one',
        variantCode: 'function passOrFail(score) {\n  if (score > 75) return "pass";\n  return "fail";\n}\n',
      },
    ],
    difficulty: 1,
    order: 3,
    variantOf: 'js-cond-01',
  },
  {
    id: 'js-cond-04',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'conditionals',
    secondaryConcepts: [],
    title: 'Speed Warning',
    statement: 'Write a function `speedWarning(speed)` that returns "slow down" if speed is greater than 60, and "ok" otherwise.',
    example: 'speedWarning(70) returns "slow down"; speedWarning(55) returns "ok".',
    starterCode: 'function speedWarning(speed) {\n  // your code here\n}\n',
    functionName: 'speedWarning',
    visibleTests: [
      { id: 't1', args: [70], expected: 'slow down' },
      { id: 't2', args: [60], expected: 'ok' },
      { id: 't3', args: [50], expected: 'ok' },
      { id: 't4', args: [61], expected: 'slow down' },
      { id: 't5', args: [90], expected: 'slow down' },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 20, max: 120 }],
      edgeCases: [[59], [60], [61], [100]],
    },
    referenceSolution: 'function speedWarning(speed) {\n  if (speed > 60) return "slow down";\n  return "ok";\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Test if the vehicle velocity exceeds sixty.',
      'Use a comparison check against sixty.',
      'Output the warning text when going too fast, otherwise okay.',
    ],
    conceptNote: 'Notice strictly greater than (>) vs greater than or equal (>=).',
    commonMistakes: [
      {
        tag: 'boundary_off_by_one',
        variantCode: 'function speedWarning(speed) {\n  if (speed >= 60) return "slow down";\n  return "ok";\n}\n',
      },
    ],
    difficulty: 1,
    order: 4,
    variantOf: 'js-cond-01',
  },
  {
    id: 'js-cond-05',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'conditionals',
    secondaryConcepts: [],
    title: 'Water State',
    statement: 'Write a function `waterState(temp)` that returns "ice" if temperature is 0 or below, "steam" if 100 or above, and "liquid" otherwise.',
    example: 'waterState(-5) returns "ice"; waterState(100) returns "steam"; waterState(25) returns "liquid".',
    starterCode: 'function waterState(temp) {\n  // your code here\n}\n',
    functionName: 'waterState',
    visibleTests: [
      { id: 't1', args: [-5], expected: 'ice' },
      { id: 't2', args: [0], expected: 'ice' },
      { id: 't3', args: [25], expected: 'liquid' },
      { id: 't4', args: [100], expected: 'steam' },
      { id: 't5', args: [110], expected: 'steam' },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: -20, max: 150 }],
      edgeCases: [[-10], [0], [1], [99], [100], [101]],
    },
    referenceSolution: 'function waterState(temp) {\n  if (temp <= 0) return "ice";\n  if (temp >= 100) return "steam";\n  return "liquid";\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Compare against the freezing point and boiling point.',
      'Check if cold enough for ice or hot enough for vapor.',
      'Output ice, steam, or liquid depending on which range holds.',
    ],
    conceptNote: 'Branch on freezing and boiling thresholds.',
    commonMistakes: [
      {
        tag: 'boundary_off_by_one',
        variantCode: 'function waterState(temp) {\n  if (temp < 0) return "ice";\n  if (temp > 100) return "steam";\n  return "liquid";\n}\n',
      },
    ],
    difficulty: 1,
    order: 5,
    variantOf: 'js-cond-01',
  },

  // ================= LOOPS =================
  {
    id: 'js-loops-01',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'loops',
    secondaryConcepts: [],
    title: 'Add up to n',
    statement: 'Write a function `sumUpTo(n)` that returns the sum of all whole numbers from 1 up to n. Use a `for` loop. If n is 0, return 0.',
    example: 'sumUpTo(4) returns 10, because 1 + 2 + 3 + 4 = 10.',
    starterCode: 'function sumUpTo(n) {\n  // your code here\n}\n',
    functionName: 'sumUpTo',
    visibleTests: [
      { id: 't1', args: [1], expected: 1 },
      { id: 't2', args: [5], expected: 15 },
      { id: 't3', args: [10], expected: 55 },
      { id: 't4', args: [0], expected: 0 },
      { id: 't5', args: [100], expected: 5050 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 0, max: 200 }],
      edgeCases: [[0], [1], [2], [199], [200]],
    },
    referenceSolution: 'function sumUpTo(n) {\n  let total = 0;\n  for (let i = 1; i <= n; i++) {\n    total += i;\n  }\n  return total;\n}\n',
    requiredConstructs: ['for_loop'],
    prewrittenHints: [
      'Look at the first test that did not pass. Is your answer too small or too big?',
      'A loop repeats steps. Start a running total variable before the loop.',
      'Add each consecutive number into your accumulator variable as you count up.',
    ],
    conceptNote: 'A for loop repeats a block of code with a counter variable. Declare the accumulator outside the loop.',
    commonMistakes: [
      {
        tag: 'loop_stops_early',
        variantCode: 'function sumUpTo(n) {\n  let total = 0;\n  for (let i = 1; i < n; i++) {\n    total += i;\n  }\n  return total;\n}\n',
      },
      {
        tag: 'assign_instead_of_add',
        variantCode: 'function sumUpTo(n) {\n  let total = 0;\n  for (let i = 1; i <= n; i++) {\n    total = i;\n  }\n  return total;\n}\n',
      },
    ],
    difficulty: 1,
    order: 1,
  },
  {
    id: 'js-loops-02',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'loops',
    secondaryConcepts: [],
    title: 'Factorial of n',
    statement: 'Write a function `factorial(n)` that calculates the product of numbers from 1 to n using a `for` loop. If n is 0 or 1, return 1.',
    example: 'factorial(4) returns 24, because 1 * 2 * 3 * 4 = 24.',
    starterCode: 'function factorial(n) {\n  // your code here\n}\n',
    functionName: 'factorial',
    visibleTests: [
      { id: 't1', args: [1], expected: 1 },
      { id: 't2', args: [3], expected: 6 },
      { id: 't3', args: [4], expected: 24 },
      { id: 't4', args: [5], expected: 120 },
      { id: 't5', args: [0], expected: 1 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 0, max: 10 }],
      edgeCases: [[0], [1], [6], [8]],
    },
    referenceSolution: 'function factorial(n) {\n  let res = 1;\n  for (let i = 2; i <= n; i++) {\n    res *= i;\n  }\n  return res;\n}\n',
    requiredConstructs: ['for_loop'],
    prewrittenHints: [
      'In a product accumulator, what should the starting value be?',
      'Start the product at one instead of zero so multiplication works.',
      'Multiply the accumulated product by each number in sequence.',
    ],
    conceptNote: 'When accumulating products, initialize to 1 because multiplying by 0 results in 0.',
    commonMistakes: [
      {
        tag: 'assign_instead_of_add',
        variantCode: 'function factorial(n) {\n  let res = 1;\n  for (let i = 1; i <= n; i++) {\n    res = i;\n  }\n  return res;\n}\n',
      },
    ],
    difficulty: 1,
    order: 2,
    variantOf: 'js-loops-01',
  },
  {
    id: 'js-loops-03',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'loops',
    secondaryConcepts: [],
    title: 'Sum Multiples of Three',
    statement: 'Write a function `sumMultiplesOfThree(n)` that returns the sum of all numbers between 1 and n that are divisible by 3. Use a `for` loop.',
    example: 'sumMultiplesOfThree(10) returns 18 (3 + 6 + 9).',
    starterCode: 'function sumMultiplesOfThree(n) {\n  // your code here\n}\n',
    functionName: 'sumMultiplesOfThree',
    visibleTests: [
      { id: 't1', args: [10], expected: 18 },
      { id: 't2', args: [3], expected: 3 },
      { id: 't3', args: [2], expected: 0 },
      { id: 't4', args: [12], expected: 30 },
      { id: 't5', args: [0], expected: 0 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 0, max: 50 }],
      edgeCases: [[0], [3], [6], [9], [30]],
    },
    referenceSolution: 'function sumMultiplesOfThree(n) {\n  let total = 0;\n  for (let i = 1; i <= n; i++) {\n    if (i % 3 === 0) total += i;\n  }\n  return total;\n}\n',
    requiredConstructs: ['for_loop'],
    prewrittenHints: [
      'Use the modulo operator to test if a number is divisible by three.',
      'Check if the current number has no remainder when divided by three.',
      'Only add the number to the sum when it is a multiple.',
    ],
    conceptNote: 'Combine loops with conditional checks inside the loop body.',
    commonMistakes: [
      {
        tag: 'loop_stops_early',
        variantCode: 'function sumMultiplesOfThree(n) {\n  let total = 0;\n  for (let i = 1; i < n; i++) {\n    if (i % 3 === 0) total += i;\n  }\n  return total;\n}\n',
      },
    ],
    difficulty: 1,
    order: 3,
    variantOf: 'js-loops-01',
  },
  {
    id: 'js-loops-04',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'loops',
    secondaryConcepts: [],
    title: 'Count Evens up to n',
    statement: 'Write a function `countEvensUpTo(n)` that counts how many even whole numbers exist between 1 and n. Use a `for` loop.',
    example: 'countEvensUpTo(6) returns 3 (2, 4, 6).',
    starterCode: 'function countEvensUpTo(n) {\n  // your code here\n}\n',
    functionName: 'countEvensUpTo',
    visibleTests: [
      { id: 't1', args: [6], expected: 3 },
      { id: 't2', args: [1], expected: 0 },
      { id: 't3', args: [2], expected: 1 },
      { id: 't4', args: [10], expected: 5 },
      { id: 't5', args: [7], expected: 3 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 0, max: 100 }],
      edgeCases: [[0], [1], [2], [100]],
    },
    referenceSolution: 'function countEvensUpTo(n) {\n  let count = 0;\n  for (let i = 1; i <= n; i++) {\n    if (i % 2 === 0) count++;\n  }\n  return count;\n}\n',
    requiredConstructs: ['for_loop'],
    prewrittenHints: [
      'An even number leaves remainder zero when divided by two.',
      'Increment a counter variable by one whenever an even is encountered.',
      'Yield the accumulated count after finishing the loop.',
    ],
    conceptNote: 'Counting increments a variable by 1, whereas summing adds the value itself.',
    commonMistakes: [
      {
        tag: 'assign_instead_of_add',
        variantCode: 'function countEvensUpTo(n) {\n  let count = 0;\n  for (let i = 1; i <= n; i++) {\n    if (i % 2 === 0) count = i;\n  }\n  return count;\n}\n',
      },
    ],
    difficulty: 1,
    order: 4,
    variantOf: 'js-loops-01',
  },
  {
    id: 'js-loops-05',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'loops',
    secondaryConcepts: [],
    title: 'Sum of Squares',
    statement: 'Write a function `sumSquares(n)` that returns the sum of the squares of whole numbers from 1 to n (1*1 + 2*2 + ... + n*n). Use a `for` loop.',
    example: 'sumSquares(3) returns 14 (1 + 4 + 9).',
    starterCode: 'function sumSquares(n) {\n  // your code here\n}\n',
    functionName: 'sumSquares',
    visibleTests: [
      { id: 't1', args: [3], expected: 14 },
      { id: 't2', args: [1], expected: 1 },
      { id: 't3', args: [4], expected: 30 },
      { id: 't4', args: [0], expected: 0 },
      { id: 't5', args: [5], expected: 55 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intInRange', min: 0, max: 30 }],
      edgeCases: [[0], [1], [2], [10]],
    },
    referenceSolution: 'function sumSquares(n) {\n  let total = 0;\n  for (let i = 1; i <= n; i++) {\n    total += i * i;\n  }\n  return total;\n}\n',
    requiredConstructs: ['for_loop'],
    prewrittenHints: [
      'The square of a number is found by multiplying it by itself.',
      'Add the squared value of the current number to your running total.',
      'Count through each number and yield the accumulated sum.',
    ],
    conceptNote: 'You can perform calculations on the counter variable before adding it.',
    commonMistakes: [
      {
        tag: 'loop_stops_early',
        variantCode: 'function sumSquares(n) {\n  let total = 0;\n  for (let i = 1; i < n; i++) {\n    total += i * i;\n  }\n  return total;\n}\n',
      },
    ],
    difficulty: 1,
    order: 5,
    variantOf: 'js-loops-01',
  },

  // ================= FUNCTIONS =================
  {
    id: 'js-func-01',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'functions',
    secondaryConcepts: [],
    title: 'Maximum of Three',
    statement: 'Write a function `maxOfThree(a, b, c)` that takes three numbers and returns the largest one.',
    example: 'maxOfThree(5, 12, 9) returns 12.',
    starterCode: 'function maxOfThree(a, b, c) {\n  // your code here\n}\n',
    functionName: 'maxOfThree',
    visibleTests: [
      { id: 't1', args: [5, 12, 9], expected: 12 },
      { id: 't2', args: [20, 10, 5], expected: 20 },
      { id: 't3', args: [1, 2, 8], expected: 8 },
      { id: 't4', args: [7, 7, 7], expected: 7 },
      { id: 't5', args: [-5, -2, -10], expected: -2 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: -50, max: 50 },
        { gen: 'intInRange', min: -50, max: 50 },
        { gen: 'intInRange', min: -50, max: 50 },
      ],
      edgeCases: [[1, 2, 3], [3, 2, 1], [2, 3, 1], [0, 0, 0]],
    },
    referenceSolution: 'function maxOfThree(a, b, c) {\n  let m = a;\n  if (b > m) m = b;\n  if (c > m) m = c;\n  return m;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Keep track of the highest value seen so far.',
      'Compare the other arguments against your current highest.',
      'Yield the overall highest number.',
    ],
    conceptNote: 'Functions receive arguments in parameters. You can inspect all arguments and return one result.',
    commonMistakes: [
      {
        tag: 'compares_only_two',
        variantCode: 'function maxOfThree(a, b, c) {\n  return a > b ? a : b;\n}\n',
      },
    ],
    difficulty: 1,
    order: 1,
  },
  {
    id: 'js-func-02',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'functions',
    secondaryConcepts: [],
    title: 'Minimum of Three',
    statement: 'Write a function `minOfThree(a, b, c)` that takes three numbers and returns the smallest one.',
    example: 'minOfThree(5, 12, 9) returns 5.',
    starterCode: 'function minOfThree(a, b, c) {\n  // your code here\n}\n',
    functionName: 'minOfThree',
    visibleTests: [
      { id: 't1', args: [5, 12, 9], expected: 5 },
      { id: 't2', args: [20, 10, 5], expected: 5 },
      { id: 't3', args: [1, 2, 8], expected: 1 },
      { id: 't4', args: [7, 7, 7], expected: 7 },
      { id: 't5', args: [-5, -2, -10], expected: -10 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: -50, max: 50 },
        { gen: 'intInRange', min: -50, max: 50 },
        { gen: 'intInRange', min: -50, max: 50 },
      ],
      edgeCases: [[1, 2, 3], [3, 2, 1], [2, 1, 3], [0, 0, 0]],
    },
    referenceSolution: 'function minOfThree(a, b, c) {\n  let m = a;\n  if (b < m) m = b;\n  if (c < m) m = c;\n  return m;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Keep track of the smallest value seen so far.',
      'Compare the other arguments against your current smallest.',
      'Yield the overall lowest number.',
    ],
    conceptNote: 'Finding the minimum follows the inverse logic of finding the maximum.',
    commonMistakes: [
      {
        tag: 'compares_only_two',
        variantCode: 'function minOfThree(a, b, c) {\n  return a < b ? a : b;\n}\n',
      },
    ],
    difficulty: 1,
    order: 2,
    variantOf: 'js-func-01',
  },
  {
    id: 'js-func-03',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'functions',
    secondaryConcepts: [],
    title: 'Clamp a Value',
    statement: 'Write a function `clamp(val, min, max)` that returns `min` if `val < min`, `max` if `val > max`, otherwise returns `val`.',
    example: 'clamp(15, 0, 10) returns 10; clamp(-5, 0, 10) returns 0; clamp(7, 0, 10) returns 7.',
    starterCode: 'function clamp(val, min, max) {\n  // your code here\n}\n',
    functionName: 'clamp',
    visibleTests: [
      { id: 't1', args: [15, 0, 10], expected: 10 },
      { id: 't2', args: [-5, 0, 10], expected: 0 },
      { id: 't3', args: [7, 0, 10], expected: 7 },
      { id: 't4', args: [0, 0, 10], expected: 0 },
      { id: 't5', args: [10, 0, 10], expected: 10 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: -50, max: 50 },
        { gen: 'intInRange', min: -20, max: 0 },
        { gen: 'intInRange', min: 1, max: 30 },
      ],
      edgeCases: [[5, 0, 10], [-10, -5, 5], [20, -5, 5]],
    },
    referenceSolution: 'function clamp(val, min, max) {\n  if (val < min) return min;\n  if (val > max) return max;\n  return val;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Check if the input falls outside the boundaries.',
      'Output the lower bound if too small, or the upper bound if too large.',
      'Otherwise preserve the original input value.',
    ],
    conceptNote: 'Clamping restricts numbers within allowed upper and lower bounds.',
    commonMistakes: [
      {
        tag: 'missing_bound',
        variantCode: 'function clamp(val, min, max) {\n  if (val < min) return min;\n  return val;\n}\n',
      },
    ],
    difficulty: 1,
    order: 3,
    variantOf: 'js-func-01',
  },
  {
    id: 'js-func-04',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'functions',
    secondaryConcepts: [],
    title: 'Absolute Difference',
    statement: 'Write a function `absDiff(a, b)` that returns the positive difference between two numbers (distance between them).',
    example: 'absDiff(10, 4) returns 6; absDiff(3, 9) returns 6.',
    starterCode: 'function absDiff(a, b) {\n  // your code here\n}\n',
    functionName: 'absDiff',
    visibleTests: [
      { id: 't1', args: [10, 4], expected: 6 },
      { id: 't2', args: [3, 9], expected: 6 },
      { id: 't3', args: [5, 5], expected: 0 },
      { id: 't4', args: [-2, 5], expected: 7 },
      { id: 't5', args: [0, 8], expected: 8 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: -50, max: 50 },
        { gen: 'intInRange', min: -50, max: 50 },
      ],
      edgeCases: [[0, 0], [10, 10], [-5, 5]],
    },
    referenceSolution: 'function absDiff(a, b) {\n  if (a >= b) return a - b;\n  return b - a;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Subtract the smaller value from the larger one.',
      'Take away the lower number from the higher number so the result is positive.',
      'Ensure the resulting distance is never negative.',
    ],
    conceptNote: 'Absolute difference represents the non-negative distance between two values.',
    commonMistakes: [
      {
        tag: 'wrong_operator',
        variantCode: 'function absDiff(a, b) {\n  return a - b;\n}\n',
      },
    ],
    difficulty: 1,
    order: 4,
    variantOf: 'js-func-01',
  },
  {
    id: 'js-func-05',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'functions',
    secondaryConcepts: [],
    title: 'Average of Three',
    statement: 'Write a function `averageOfThree(a, b, c)` that calculates and returns the arithmetic mean of three numbers.',
    example: 'averageOfThree(3, 6, 9) returns 6.',
    starterCode: 'function averageOfThree(a, b, c) {\n  // your code here\n}\n',
    functionName: 'averageOfThree',
    visibleTests: [
      { id: 't1', args: [3, 6, 9], expected: 6 },
      { id: 't2', args: [10, 20, 30], expected: 20 },
      { id: 't3', args: [0, 0, 0], expected: 0 },
      { id: 't4', args: [4, 4, 4], expected: 4 },
      { id: 't5', args: [1, 2, 3], expected: 2 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intInRange', min: 0, max: 90 },
        { gen: 'intInRange', min: 0, max: 90 },
        { gen: 'intInRange', min: 0, max: 90 },
      ],
      edgeCases: [[0, 0, 0], [3, 3, 3], [10, 20, 30]],
    },
    referenceSolution: 'function averageOfThree(a, b, c) {\n  return (a + b + c) / 3;\n}\n',
    requiredConstructs: [],
    prewrittenHints: [
      'Add all three numbers together first inside parentheses.',
      'Divide the combined total by three.',
      'Calculate the arithmetic mean by dividing the sum by the count of items.',
    ],
    conceptNote: 'Use parentheses to ensure addition occurs before division.',
    commonMistakes: [
      {
        tag: 'wrong_operator',
        variantCode: 'function averageOfThree(a, b, c) {\n  return a + b + c / 3;\n}\n',
      },
    ],
    difficulty: 1,
    order: 5,
    variantOf: 'js-func-01',
  },

  // ================= ARRAYS & LISTS =================
  {
    id: 'js-arr-01',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'arrays_lists',
    secondaryConcepts: [],
    title: 'Sum of Even Numbers',
    statement: 'Write a function `sumOfEvens(numbers)` that returns the sum of all even numbers in an array. Use a loop.',
    example: 'sumOfEvens([1, 2, 3, 4, 5, 6]) returns 12 (2 + 4 + 6).',
    starterCode: 'function sumOfEvens(numbers) {\n  // your code here\n}\n',
    functionName: 'sumOfEvens',
    visibleTests: [
      { id: 't1', args: [[1, 2, 3, 4, 5, 6]], expected: 12 },
      { id: 't2', args: [[1, 3, 5]], expected: 0 },
      { id: 't3', args: [[2, 4, 6]], expected: 12 },
      { id: 't4', args: [[]], expected: 0 },
      { id: 't5', args: [[10, -2, 5]], expected: 8 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intArray', minLen: 0, maxLen: 12, min: -20, max: 20 }],
      edgeCases: [[[]], [[2]], [[1]], [[2, 4, 6, 8]]],
    },
    referenceSolution: 'function sumOfEvens(numbers) {\n  let total = 0;\n  for (let i = 0; i < numbers.length; i++) {\n    if (numbers[i] % 2 === 0) total += numbers[i];\n  }\n  return total;\n}\n',
    requiredConstructs: ['any_loop'],
    prewrittenHints: [
      'Iterate through the array elements with a loop.',
      'Test each element with modulo two to see if it is even.',
      'Add the even elements into your running total.',
    ],
    conceptNote: 'Arrays store multiple items in order. Access items by index starting at 0 up to length - 1.',
    commonMistakes: [
      {
        tag: 'counts_instead_of_sums',
        variantCode: 'function sumOfEvens(numbers) {\n  let total = 0;\n  for (let i = 0; i < numbers.length; i++) {\n    if (numbers[i] % 2 === 0) total++;\n  }\n  return total;\n}\n',
      },
    ],
    difficulty: 1,
    order: 1,
  },
  {
    id: 'js-arr-02',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'arrays_lists',
    secondaryConcepts: [],
    title: 'Count Positives',
    statement: 'Write a function `countPositives(numbers)` that returns how many numbers in the array are strictly greater than 0. Use a loop.',
    example: 'countPositives([-1, 4, 0, 7, -3]) returns 2.',
    starterCode: 'function countPositives(numbers) {\n  // your code here\n}\n',
    functionName: 'countPositives',
    visibleTests: [
      { id: 't1', args: [[-1, 4, 0, 7, -3]], expected: 2 },
      { id: 't2', args: [[1, 2, 3]], expected: 3 },
      { id: 't3', args: [[-1, -2]], expected: 0 },
      { id: 't4', args: [[]], expected: 0 },
      { id: 't5', args: [[0, 0, 5]], expected: 1 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intArray', minLen: 0, maxLen: 12, min: -20, max: 20 }],
      edgeCases: [[[]], [[1]], [[-1]], [[0]]],
    },
    referenceSolution: 'function countPositives(numbers) {\n  let count = 0;\n  for (let i = 0; i < numbers.length; i++) {\n    if (numbers[i] > 0) count++;\n  }\n  return count;\n}\n',
    requiredConstructs: ['any_loop'],
    prewrittenHints: [
      'Initialize a counter variable to zero.',
      'Inspect each array item and check if it is greater than zero.',
      'Increment your counter by one for each positive number found.',
    ],
    conceptNote: 'Zero is neither positive nor negative.',
    commonMistakes: [
      {
        tag: 'boundary_off_by_one',
        variantCode: 'function countPositives(numbers) {\n  let count = 0;\n  for (let i = 0; i < numbers.length; i++) {\n    if (numbers[i] >= 0) count++;\n  }\n  return count;\n}\n',
      },
    ],
    difficulty: 1,
    order: 2,
    variantOf: 'js-arr-01',
  },
  {
    id: 'js-arr-03',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'arrays_lists',
    secondaryConcepts: [],
    title: 'Find Maximum in Array',
    statement: 'Write a function `findMax(numbers)` that returns the largest number in a non-empty array. Use a loop.',
    example: 'findMax([3, 9, 2, 5]) returns 9.',
    starterCode: 'function findMax(numbers) {\n  // your code here\n}\n',
    functionName: 'findMax',
    visibleTests: [
      { id: 't1', args: [[3, 9, 2, 5]], expected: 9 },
      { id: 't2', args: [[7]], expected: 7 },
      { id: 't3', args: [[-5, -1, -10]], expected: -1 },
      { id: 't4', args: [[10, 20, 30]], expected: 30 },
      { id: 't5', args: [[100, 50, 20]], expected: 100 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intArray', minLen: 1, maxLen: 10, min: -50, max: 50 }],
      edgeCases: [[[5]], [[-10, -5, -20]], [[1, 2, 3, 4]]],
    },
    referenceSolution: 'function findMax(numbers) {\n  let m = numbers[0];\n  for (let i = 1; i < numbers.length; i++) {\n    if (numbers[i] > m) m = numbers[i];\n  }\n  return m;\n}\n',
    requiredConstructs: ['any_loop'],
    prewrittenHints: [
      'Initialize your max variable with the very first item of the array.',
      'Compare each subsequent element against that running maximum.',
      'Update your maximum whenever a larger number is seen.',
    ],
    conceptNote: 'Starting with numbers[0] ensures negative numbers are handled correctly.',
    commonMistakes: [
      {
        tag: 'loop_stops_early',
        variantCode: 'function findMax(numbers) {\n  let m = numbers[0];\n  for (let i = 1; i < numbers.length - 1; i++) {\n    if (numbers[i] > m) m = numbers[i];\n  }\n  return m;\n}\n',
      },
    ],
    difficulty: 1,
    order: 3,
    variantOf: 'js-arr-01',
  },
  {
    id: 'js-arr-04',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'arrays_lists',
    secondaryConcepts: [],
    title: 'Sum All Array Elements',
    statement: 'Write a function `sumArray(numbers)` that returns the sum of all numbers in the array. Return 0 if the array is empty. Use a loop.',
    example: 'sumArray([2, 4, 6]) returns 12.',
    starterCode: 'function sumArray(numbers) {\n  // your code here\n}\n',
    functionName: 'sumArray',
    visibleTests: [
      { id: 't1', args: [[2, 4, 6]], expected: 12 },
      { id: 't2', args: [[]], expected: 0 },
      { id: 't3', args: [[10]], expected: 10 },
      { id: 't4', args: [[-3, 3]], expected: 0 },
      { id: 't5', args: [[1, 2, 3, 4, 5]], expected: 15 },
    ],
    hiddenTests: {
      count: 20,
      args: [{ gen: 'intArray', minLen: 0, maxLen: 12, min: -20, max: 20 }],
      edgeCases: [[[]], [[0]], [[10, 20, 30]]],
    },
    referenceSolution: 'function sumArray(numbers) {\n  let total = 0;\n  for (let i = 0; i < numbers.length; i++) {\n    total += numbers[i];\n  }\n  return total;\n}\n',
    requiredConstructs: ['any_loop'],
    prewrittenHints: [
      'Start an accumulator variable at zero.',
      'Loop across the array and add each item to your total.',
      'Output the final sum once all items are visited.',
    ],
    conceptNote: 'Accumulate array elements into a sum variable.',
    commonMistakes: [
      {
        tag: 'counts_instead_of_sums',
        variantCode: 'function sumArray(numbers) {\n  let total = 0;\n  for (let i = 0; i < numbers.length; i++) {\n    total++;\n  }\n  return total;\n}\n',
      },
    ],
    difficulty: 1,
    order: 4,
    variantOf: 'js-arr-01',
  },
  {
    id: 'js-arr-05',
    language: 'javascript',
    type: 'write_function',
    primaryConcept: 'arrays_lists',
    secondaryConcepts: [],
    title: 'Count Occurrences',
    statement: 'Write a function `countOccurrences(arr, target)` that returns how many times `target` appears in array `arr`. Use a loop.',
    example: 'countOccurrences([1, 2, 2, 3, 2], 2) returns 3.',
    starterCode: 'function countOccurrences(arr, target) {\n  // your code here\n}\n',
    functionName: 'countOccurrences',
    visibleTests: [
      { id: 't1', args: [[1, 2, 2, 3, 2], 2], expected: 3 },
      { id: 't2', args: [[1, 2, 3], 4], expected: 0 },
      { id: 't3', args: [[], 5], expected: 0 },
      { id: 't4', args: [[7, 7, 7], 7], expected: 3 },
      { id: 't5', args: [[0, 1, 0], 0], expected: 2 },
    ],
    hiddenTests: {
      count: 20,
      args: [
        { gen: 'intArray', minLen: 0, maxLen: 12, min: 0, max: 5 },
        { gen: 'intInRange', min: 0, max: 5 },
      ],
      edgeCases: [[[], 1], [[1], 1], [[1], 2]],
    },
    referenceSolution: 'function countOccurrences(arr, target) {\n  let count = 0;\n  for (let i = 0; i < arr.length; i++) {\n    if (arr[i] === target) count++;\n  }\n  return count;\n}\n',
    requiredConstructs: ['any_loop'],
    prewrittenHints: [
      'Initialize a match counter to zero.',
      'Inspect each array item to check if it equals the search item.',
      'Increment your counter each time an identical item is found.',
    ],
    conceptNote: 'Search and count elements matching a specific target value.',
    commonMistakes: [
      {
        tag: 'loop_stops_early',
        variantCode: 'function countOccurrences(arr, target) {\n  let count = 0;\n  for (let i = 0; i < arr.length - 1; i++) {\n    if (arr[i] === target) count++;\n  }\n  return count;\n}\n',
      },
    ],
    difficulty: 1,
    order: 5,
    variantOf: 'js-arr-01',
  },
];
